services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "127.0.0.1:9100:9100"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
